# Gamnina 2000 Forge splash theme
enabled=true
rotate=false
showMemory=true
background=0x120622
font=0xF4EEFF
barBorder=0x63EFFF
bar=0xD718A1
barBackground=0x2D0B46
memoryGood=0x4DEB76
memoryWarn=0xF4D64E
memoryLow=0xFF416C
resourcePackPath=resources
logoOffset=171
forgeTexture=fml\:textures/gui/gamnina_splash.png
fontTexture=textures/font/ascii.png
